version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Running linters and type checks..."
      - npm run lint
      - npm run typecheck
  # 빌드를 수행할 명령을 입력합니다.
  build:
    commands:
      - echo "Building the Next.js app..."
      - next build --standalone
  post_build:
    commands:
      - echo Build Phase >> Build completed on `date`
# 빌드 결과물로 나온 아티팩트에 대한 정보를 제공합니다.
artifacts:
  files:
    - '.next/**/*' # 빌드된 Next.js 애플리케이션 파일
    - 'public/**/*' # public 폴더 내의 정적 파일
    - 'package.json' # npm install을 위해 필요
  discard-paths: yes
