version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Running linters and type checks..."
      - npm run typecheck
  # 빌드를 수행할 명령 입력
  build:
    commands:
      - echo "Building the Next.js app..."
      - npm run build:standalone
  post_build:
    commands:
      - echo Build Phase >> Build completed on `date`
# S3 버킷으로 업로드
artifacts:
  files:
    - '.next/**/*'
    - 'public/**/*'
    - 'package.json'
  packaging: zip
  # https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching#aws-codebuild
  cache:
    paths:
      - 'node_modules/**/*'
      - '.next/cache/**/*'
